routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//defaultnya laravel
Route::get('/', function () {
    return view('welcome');
});

//myroute
Route::get('/hello', function () {
    echo '<h1>Hello World</h1>';
});

//membuat Route mengarah ke hellocontroller
Route::get('belajar','HelloController@index');

//membuat route CRUD Siswa
Route::resource('siswa', 'SiswaController');

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $fillable = [
        'nama_siswa','alamat','no_telpon'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HelloController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloController extends Controller
{
    //membuat index 
    public function index()
    {
        $nama  = "Disini Isi Nama Kalian";
        $pelajaran =["Algoritma", "Database","Web", "Mobile","Jaringan",
        "Data Mining","Hybrid Mobile"];

       return view('hello', compact('nama','pelajaran'));
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Siswa;
use Illuminate\Http\Request;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //Select * FROM siswa;
        $siswa = Siswa::all();
        return view('siswa.index', compact('siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //untuk validasi input text
        $request->validate([
            'nama_siswa' => 'required',
            'alamat'    => 'required',
            'no_telpon' => 'required'
        ]);
        //fungsi untuk simpan ke dalam database
        // INSERT INTO siswa(nama_field) VALUES(nama_value);
        Siswa::create($request->all());
        return redirect()->route('siswa.index')->with('Siswa Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function show(Siswa $siswa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function edit(Siswa $siswa)
    {
        //menampilkan form update 
        return view('siswa.edit', compact('siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Siswa $siswa)
    {
        //validate data input 
        $request->validate([
            'nama_siswa' => 'required',
            'alamat' => 'required',
            'no_telpon'=>'required'
        ]);
        //fungsi update database
        $siswa->update($request->all());
        return redirect()->route('siswa.index')->with('Siswa Berhasil Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Siswa $siswa)
    {
        //fungsi untuk delete field database
        $siswa->delete();
        return redirect()->route('siswa.index')->with('Siswa Berhasil Di Hapus');
    }
}

resources/views/hello.blade.php
<h1>Text Ini Berasal gabungan controller dan Views</h1>
<br>
<p>{{ $nama }}</p>

<ul>
    @foreach ($pelajaran as $pl)
        <li>{{ $pl }}</li>
    @endforeach
</ul>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
    <title>Layout Master</title>
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
</body>
</html>

resources/views/siswa/create.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>New Siswa</h2>
            </div>
            <div class="pull-right">
                <a href="{{ route('siswa.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Data:</strong> not save <br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('siswa.store')}}" method="post">
            @csrf
            <div class="row">
                <div class="col-xs-12 col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="#">Nama Siswa</label>
                        <input type="text" name="nama_siswa" class="form-control"
                         placeholder="Nama Siswa">
                    </div>
                    <div class="form-group">
                        <label for="#">Alamat</label>
                        <input type="text" name="alamat" class="form-control" 
                        placeholder="Alamat">
                    </div>
                    <div class="form-group">
                        <label for="#">No Telpon</label>
                        <input type="text" name="no_telpon" class="form-control"
                         placeholder="No Telpon">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <button type="submit" class="btn btn-primary">Simpan Data</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/siswa/edit.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Update Siswa</h2>
            </div>
            <div class="pull-right">
                <a href="{{ route('siswa.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Data:</strong> not save <br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('siswa.update', $siswa->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <label for="#">Nama Siswa</label>
                        <input type="text" name="nama_siswa" class="form-control"
                         placeholder="Nama Siswa" value="{{ $siswa->nama_siswa }}">
                    </div>
                    <div class="form-group">
                        <label for="#">Alamat</label>
                        <input type="text" name="alamat" class="form-control" 
                        placeholder="Alamat" value="{{ $siswa->alamat }}">
                    </div>
                    <div class="form-group">
                        <label for="#">No Telpon</label>
                        <input type="text" name="no_telpon" class="form-control"
                         placeholder="No Telpon" value="{{ $siswa->no_telpon }}">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <button type="submit" class="btn btn-primary">Simpan Data</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/siswa/index.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel CRUD Siswa</h2>
            </div>
            <div class="pull-right">
                <a href="{{ route('siswa.create') }}" class="btn btn-success">Create Siswa</a>
            </div>
        </div>
    </div>

    @if($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>NO</th>
            <th>Nama Siswa</th>
            <th>Alamat</th>
            <th>No Telpon</th>
            <th width="280px">Action</th>
        </tr>
        @forelse ($siswa as $sw)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $sw->nama_siswa }}</td>
            <td>{{ $sw->alamat }}</td>
            <td>{{ $sw->no_telpon }}</td>
            <td>
                <form action="{{ route('siswa.destroy', $sw->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <a href="#" class="btn btn-info">Show</a>
                    <a href="{{ route('siswa.edit', $sw->id) }}" class="btn btn-warning">Update</a>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>    
        @empty
            <tr>
                <td colspan="5" class="text-center">Tidak Ada Data</td>
            </tr>
        @endforelse
        
    </table>

@endsection